name: github pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh



    - run: |
        mkdir -p out
        date >> out/index.html
        git fetch --prune --unshallow # for git describe
        git describe --dirty --always

    - uses: actions/upload-artifact@v3
      with:
        name: gh-pages
        path: out
    - uses: actions/upload-pages-artifact@v4
      with:
        path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
